language: java
jdk: oraclejdk7

install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}
after_success:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "[[ \"$TRAVIS_BRANCH\" == \"master\" ]] && mvn deploy --settings target/travis/settings.xml"

notifications:
  email: false
  webhooks:
    - http://get.spout.org/hook
    - http://n.tkte.ch/h/495/VmgKQ4ao-JPBgNiuhZc-5bHv

env:
  global:
    - secure: "i/7ILQcFGsvVn8pn/s32gwXTfYCPMSZY1djuSygM2IiUIux3XS+MpKQb9K7SM6d3lFGiuxUQ0o9hDZ1r0s4Va1HOd55/98ROEixob94y9cb/GmLmbiZAyZ19gAF7s5V/K6uqZfe4IEPuZoMMyjcQNKelxJ+kRnP9qZBDcI23ZIM="
    - secure: "V1MJQd1PR23NvIOTZAo272wMw80sRmicjUNDT9lHVxuZ65U1vjfux+UrjrB2jDSST4ylRxqj5I/DmXx0X9poQhFkjPKwMNNpbR3s5oVxM35bVz4AgmqkpNfR7zIKRg+vLVNG1EqMzSA3/rB0ll7JIxWgGocZdiYjvEkPZd4qqIM="
